### ISSUE TITLE
Can't run hardware sample code

### ISSUE THREAD

**Issue by blmalone** [intel/linux-sgx#686]
This was working recently but now I'm receiving the following error. 

```
aesmd.service - Intel(R) Architectural Enclave Service Manager
     Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-03-03 17:27:11 UTC; 1s ago
    Process: 1601 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
    Process: 1615 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 1616 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 1617 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 1618 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 1619 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 1620 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
   Main PID: 1621 (aesm_service)
      Tasks: 4 (limit: 9152)
     Memory: 3.0M
     CGroup: /system.slice/aesmd.service
             └─1621 /opt/intel/sgx-aesm-service/aesm/aesm_service

Mar 03 17:27:11 nuc systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Mar 03 17:27:11 nuc systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Mar 03 17:27:11 nuc aesm_service[1621]: [get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
Mar 03 17:27:11 nuc aesm_service[1621]: [get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
Mar 03 17:27:11 nuc aesm_service[1621]: [get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
Mar 03 17:27:11 nuc aesm_service[1621]: [load_qe ../qe_logic.cpp:641] Error, call sgx_create_enclave QE fail [load_qe], SGXError:2006.
Mar 03 17:27:11 nuc aesm_service[1621]: Failed to load QE3: 0x2006
Mar 03 17:27:11 nuc aesm_service[1621]: The server sock is 0x55f7531742c0
```

and 

```
[get_driver_type /home/blaine/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
```

**Comment by MetalGearBronya** [comment]
Hi, may I know how you solved this issue? I'm encountering the same error and found that you have closed this issue yourself. Thanks in advance!

**Comment by ltinerary** [comment]
I have an error said :**Failed to load QE3:0x4004**
 may I know how you solved this issue?

**Comment by MetalGearBronya** [comment]
I built this repo on a machine that support only SGX1 but not FLC feature and encountered the error mentioned in this issue. 
I end up did a fresh install of ubuntu 20.04, applied the patch in this link https://github.com/alibaba/inclavare-containers/tree/master/hack/no-sgx-flc and compiled with no issue. May be helpful for you.

**Comment by ltinerary** [comment]
> I built this repo on a machine that support only SGX1 but not FLC feature and encountered the error mentioned in this issue.
> I end up did a fresh install of ubuntu 20.04, applied the patch in this link https://github.com/alibaba/inclavare-containers/tree/master/hack/no-sgx-flc and compiled with no issue. May be helpful for you.

what does you mean support only SGX1？It just came to me my machine support SGX1 but not SGX2 by a test procedure。so what is SGX1 and what is SGX2?
and
I open this link,it's DCAP,but my cpu only support oot driver.
Thanks @MetalGearBronya !

**Comment by jiazhang0** [comment]
> > I built this repo on a machine that support only SGX1 but not FLC feature and encountered the error mentioned in this issue.
> > I end up did a fresh install of ubuntu 20.04, applied the patch in this link https://github.com/alibaba/inclavare-containers/tree/master/hack/no-sgx-flc and compiled with no issue. May be helpful for you.
> 
> what does you mean support only SGX1？It just came to me my machine support SGX1 but not SGX2 by a test procedure。so what is SGX1 and what is SGX2?
> and
> I open this link,it's DCAP,but my cpu only support oot driver.
> Thanks @MetalGearBronya !

The root cause of your problem is that you are attempting to run sgx sdk and psw stack on SGX1 platform **WITH sgx in-tree kernel driver** but you intend to use isgx out-of-tree driver. Maybe you don't have any impression on when the system is upgraded to support sgx in-tree driver.

Your situation may be this: platform bootup -> sgx in-tree kernel driver startup -> no-FLC detected ->  sgx in-tree kernel driver exits and clear sgx feature flag from kernel's cpu capabilities -> loading sgx oot driver (isgx) -> detecting sgx feature flag from kernel's cpu capabilities -> not set -> sgx oot driver (isgx) exits -> aesmd server startup -> attempt to open sgx device file -> not found -> error with "Failed to open Intel SGX device".

Essentially, this is all due to the fact that the sgx in-tree kernel driver completely drops the support for all sgx platforms without FLC. The patches mentioned above resolves this problem through modifying sgx in-tree kernel driver and sgx psw software. However, it is not an easy work for everyone. So I push a new patch for sgx oot driver (isgx) which can process your situation. Please follow [these steps](https://github.com/alibaba/inclavare-containers/blob/master/hack/no-sgx-flc/README.md#for-isgx-linux-driver-users) and let me know whether it is working for you. If it doesn't work. please let me know the following info:

- os version
- sgx sdk & psw version
- oot kernel driver version
- anything else you can provide

**Comment by lzha101** [comment]
We've merged a fix to the OOT driver tree. See https://github.com/intel/linux-sgx-driver/pull/133
So I think the above scenario should be supported with the OOT driver if you use the latest driver code instead of using the driver installer downloaded from 01.org.

**Comment by ltinerary** [comment]
Thank you for your efforts！  @lzha101 @jiazhang0
I'm so sorry that  the operating system was reinstalled and I tried  use DCAP driver to run the Graphene example.

So I can't verify it right now.
I will provide as much information as I can from memory.

**The information of that error(`failed load QE3`)**：

- os:ubuntu18.04
- linux kernel:5.9
- cpu:Intel(R) Core(TM) i7-10700
- OOT driver: [sgx_linux_x64_driver_2.11.0_0373e2e.bin](https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/sgx_linux_x64_driver_2.11.0_0373e2e.bin)
- sdk: [sgx_linux_x64_sdk_2.13.100.4.bin](https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/sgx_linux_x64_sdk_2.13.100.4.bin)

I'm sorry to bring you extra workload.

**Comment by jiazhang0** [comment]
> We've merged a fix to the OOT driver tree. See [intel/linux-sgx-driver#133](https://github.com/intel/linux-sgx-driver/pull/133)
> So I think the above scenario should be supported with the OOT driver if you use the latest driver code instead of using the driver installer downloaded from 01.org.

Good job! I will update the info and refer to your new solution. Thanks!

**Comment by jiazhang0** [comment]
>     * 5.9

No problem. Looks like you have already got a working environment.

**Comment by ltinerary** [comment]
> > ```
> > * 5.9
> > ```
> 
> No problem. Looks like you have already got a working environment.

In fact，I still encounter some problems:[aesm service return error:1](https://github.com/intel/linux-sgx/issues/702).😣
